### ISSUE TITLE
eslint plugin html not in package.json

### ISSUE THREAD

**Issue by orenmizr** [fishenal/Todos_Vuejs#1]
keep getting them when editing js files. any ideas ? 
might be related to node 6.x.x

**Comment by fishenal** [comment]
i init this project with vue-cli @vue2.0 version, and close eslint option when init.
you want to open eslint right? maybe you can init another blank project with vue-cli, open eslint option when init, then copy this `src` file to new project.

or ,  compare the two project,  I think to change some files in `build` `config` folders , and package.json,  may make eslint to work.
